version: "3.2"
services:
  phpa:
    build: './phpa/'
    depends_on:
      - db
      - pma
    ports:
      - "80:80"
    volumes:
      - ./web/:/var/www/
      - ./phpa/vhosts:/etc/apache2/from-host
      - ./phpa/default.conf:/etc/apache2/sites-available/000-default.conf
  db:
    image: mysql:latest
    environment:
        MYSQL_DATABASE: docker_db
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: rootpassword 
    command: --default-authentication-plugin=mysql_native_password
    ports:
      # just if you also want to access it directly from you host
      # node neede for phpmyadmin
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./db/data/:/var/lib/mysql/

  pma:
      image: phpmyadmin/phpmyadmin
      links: 
          - db:db
      ports:
          - 8000:80
      environment:
          MYSQL_USER: user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: rootpassword
      volumes:
        - ./db/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
